apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: front
    app.kubernetes.io/name: next-web
    app.kubernetes.io/part-of: web
  name: next-web
  namespace: next-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: front
      app.kubernetes.io/name: next-web
      app.kubernetes.io/part-of: web
  template:
    metadata:
      labels:
        app.kubernetes.io/component: front
        app.kubernetes.io/name: next-web
        app.kubernetes.io/part-of: web
    spec:
      containers:
        - image: ghcr.io/andes-noh/next-sample:f7e59240
          name: app
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.2"
              memory: 128M
