apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: front
    app.kubernetes.io/name: next-web
    app.kubernetes.io/part-of: web
  name: next-web
  namespace: next-web
spec:
  ports:
    - nodePort: 32756
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/component: front
    app.kubernetes.io/name: next-web
    app.kubernetes.io/part-of: web
  type: NodePort
